#开发环境配置

server:
  # 服务端口
  port: 1024


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.43.183.238:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: lh18178007095


# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug




